import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterNav from "@/components/layout/FooterNav";

const SideBar = dynamic(() => import("@/components/layout/Sidebar"), {
  ssr: false,
});
const Navigation = dynamic(() => import("@/components/layout/Navigation"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full h-auto">
          <SideBar />
          <div className="relative h-auto w-full overflow-x-hidden scrollbar-hide overflow-y-auto">
            <Navigation />
            <div className=" pl-0 md:pl-20 lg:pl-20 px-0">{children}</div>
            <FooterNav />
          </div>
        </div>
      </body>
    </html>
  );
}
